global:
  scrape_interval: 15s # Interval default untuk mengumpulkan metrik

scrape_configs:
  # 1. Self-monitoring Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Node Exporter (untuk metrik sistem VPS Anda)
  - job_name: 'node_exporter'
    # 'node-exporter' adalah nama service di docker-compose.yml
    static_configs:
      - targets: ['node-exporter:9100']